#!/bin/bash

EMAIL="7xxxx@gmail.com"

#Add to crontab -e check every 5 minutes
# m h  dom mon dow   command
#*/5 * * * * /usr/local/bin/naemon_up_check >> /var/log/naemon/naemon_up_check.log 2>&1

NAGCHK="/usr/lib/nagios/plugins/check_nagios"
PARAMS="-e 60 -F /var/log/naemon/naemon.log -C /usr/bin/naemon"
 
INFO=`$NAGCHK $PARAMS`
STATUS=$?
 
case $STATUS in
    0) echo "OK : " $INFO
        ;;
    *) echo "ERROR : " $INFO | \
            /usr/bin/mailx -s "## Naemon on $(hostname -f) Down or Error ##" $EMAIL
        ;;
esac
